name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  # Keep in sync with rust-version in Cargo.toml.
  MSRV: "1.85"

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.MSRV }}
          components: rustfmt, clippy
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo build
      - run: cargo test --all-targets --all-features
